Docker build CI for rleases
matekasse/matekasse pull request #108
Opened 2021-08-12 19:06 UTC by neilschark

2021-08-14 07:26 UTC, andresterba requested changes
Nice work!

2021-08-14 21:19 UTC, neilschark commented on .github/workflows/build-latest-docker-image.yaml
> +      - name: Build Docker image latest
AFAIK every project has a latest tag on a docker image. Nextcloud is the only one I ever used which can break if you just use latest.

2021-08-14 21:20 UTC, neilschark commented on .github/workflows/build-latest-testing-docker-image.yaml
> +  build-latest-testing-image-multiarch:
Yes, the job name is incorrect. I will change it

2021-08-14 21:20 UTC, neilschark commented on .github/workflows/build-latest-docker-image.yaml
>  name: build latest docker image
Good Idea, I will change it.

2021-08-15 10:59 UTC, neilschark commented on .github/workflows/build-latest-testing-docker-image.yaml
> +  build-latest-testing-image-multiarch:
Done

2021-08-15 11:00 UTC, neilschark commented on .github/workflows/build-latest-docker-image.yaml
>  name: build latest docker image
Done

2021-08-15 11:01 UTC, neilschark commented on .github/workflows/build-latest-docker-image.yaml
> +      - name: Build Docker image latest
I would just make sure that our project updates nicely

2021-08-15 18:13 UTC, andresterba commented on .github/workflows/build-latest-docker-image.yaml
> +      - name: Build Docker image latest
> I would just make sure that our project updates nicely

Maybe we should talk with @theErikss0n about versioning.
I would prefer basic SemVer and with that we can break with major releases.
But let's go with the latest tag for now until we have a real release canidate.

2021-08-15 18:14 UTC, andresterba approved these changes
LGTM :tada:

2021-08-15 18:15 UTC, merged