Add simple testcafe tests
matekasse/matekasse pull request #190
Opened 2021-09-22 19:12 UTC by neilschark

2021-10-02 17:00 UTC, andresterba requested changes
Good job getting this is an working state!

2021-10-03 11:39 UTC, neilschark commented on app/src/components/user-page/user-page.vue
> +        <change-user-names-modal :user="editedUser" v-model="showNamesDialog" />
eslint

2021-10-03 11:39 UTC, neilschark commented on app/src/components/user-page/user-page.vue
> +        <change-user-password-modal v-model="showPasswordDialog" />
eslint

2021-10-03 11:40 UTC, neilschark commented on testcafe/tests/admin-page-test.js
> +test('Navigation Tabs', async t => {
I have no idea if its possible.

2021-10-03 11:40 UTC, neilschark commented on testcafe/tests/admin-page-test.js
> +test('Navigation Tabs', async t => {
But its expressive. It tests if you can navigate through the admin view: "Admin View Navigation"

2021-10-06 17:16 UTC, merged